"""Repository rule to expose Python version from pyproject.toml."""

_EXTRACTOR_SCRIPT = Label("//python/private:pyproject_version_extractor.py")

def _pyproject_version_repo_impl(rctx):
    """Create a repository that exports PYTHON_VERSION from pyproject.toml."""
    pyproject_path = rctx.path(rctx.attr.pyproject_toml)
    rctx.read(pyproject_path, watch = "yes")

    # Use the shared extractor script
    extractor = rctx.path(_EXTRACTOR_SCRIPT)
    result = rctx.execute([
        "python3",
        str(extractor),
        str(pyproject_path),
    ])

    if result.return_code != 0:
        fail("Failed to read Python version from pyproject.toml: " + result.stderr)

    version = result.stdout.strip()

    # Create a .bzl file that exports the version
    rctx.file("version.bzl", """
\"\"\"Python version from pyproject.toml.

This file is automatically generated. Do not edit.
\"\"\"

PYTHON_VERSION = "{version}"
""".format(version = version))

    rctx.file("BUILD.bazel", """
# Automatically generated from pyproject.toml
exports_files(["version.bzl"])
""")

pyproject_version_repo = repository_rule(
    implementation = _pyproject_version_repo_impl,
    attrs = {
        "pyproject_toml": attr.label(
            mandatory = True,
            allow_single_file = True,
            doc = "Label pointing to pyproject.toml file.",
        ),
    },
    doc = """Repository rule that reads Python version from pyproject.toml.

This rule creates a repository with a `version.bzl` file that exports
`PYTHON_VERSION` constant. This allows BUILD files to import the Python
version without hardcoding it.

Example:
```python
    load("@python_version_from_pyproject//:version.bzl", "PYTHON_VERSION")

    compile_pip_requirements(
        name = "requirements",
        python_version = PYTHON_VERSION,
        requirements_txt = "requirements.txt",
    )
```
""",
)
